version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/meme-server
hooks:
  ApplicationStop:
    - location: deployment_scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: deployment_scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deployment_scripts/application_start.sh
      timeout: 300
      runas: ubuntu