
-- public account
INSERT INTO public.account (uid, email, username) VALUES ('zLMEK11qxWhsXUpzIMqgoCpci8E2', 'dirk.metacore@gmail.com', 'dirk.metacore');
INSERT INTO public.account (uid, email, username) VALUES ('IjjE2ni5MVPcGdZ0Mw1w0kMV9fE2', 'stroan20@gmail.com', 'TheRao');
INSERT INTO public.account (uid, email, username) VALUES ('NgsV6IFDYwVHWxyt2OORgVCDQNJ3', 'raoframe@gmail.com', 'arron');
INSERT INTO public.account (uid, email, username) VALUES ('tA95AUhYCIY4qerK1Ez4kLuDyyj2', 'stroan93@gmail.com', 'arronstr');
INSERT INTO public.account (uid, email, username) VALUES ('Ujti1yOL0MhtOh5yJ6clkGE2wW62', 'rao@metacorehealth.com', 'raos');
INSERT INTO public.account (uid, email, username) VALUES ('mIi5ID1RmLNX6aFGohu9Uo78sKh2', 'mariatua2@gmail.com', 'marytesting');
INSERT INTO public.account (uid, email, username) VALUES ('aZzV1UA48bWc4T68OO3elYVFyUq1', 'mvortizr@gmail.com', 'mary');
INSERT INTO public.account (uid, email, username) VALUES ('Rpc4ahEL3HZcRUkPhgdNF0CQ4H33', 'marytest1@gmail.com', 'marytest1');
INSERT INTO public.account (uid, email, username) VALUES ('EUA0N8p3RlYL7LBuZgOskmkeBsH2', 'marytest2@gmail.com', 'marytest2');
INSERT INTO public.account (uid, email, username) VALUES ('OYwvaE1UO2fH6I6J6MWsGxZeoMH2', 'marytesting123@gmail.com', 'marytesting123');
INSERT INTO public.account (uid, email, username) VALUES ('fSQ9CAMcQARz3A739SXz2sJnsSw2', 'mary7@gmail.com', 'mary7');
INSERT INTO public.account (uid, email, username) VALUES ('HHcTqTMHpLX0gA6IESQKCmWqKoC3', 'straodev@gmail.com', 'reckoners');
INSERT INTO public.account (uid, email, username) VALUES ('6sjxrjS6hdO1v0v8qU5kZEuUoog2', 'patrick.buchanan.dugan@gmail.com', 'duganist');
INSERT INTO public.account (uid, email, username) VALUES ('kWcObECxVucz6I3IjvfQocj4mi22', 'rivara.eugenia@gmail.com', 'euge');
INSERT INTO public.account (uid, email, username) VALUES ('KUs75zHZVDWrRbPusMJIMz1Aaqi2', 'shawn@gmail.com', 'shawn');
INSERT INTO public.account (uid, email, username) VALUES ('y0NGSz1XkAexvTlTNSU6rzKhtbC3', '13-11020@usb.ve', 'marya');
INSERT INTO public.account (uid, email, username) VALUES ('bw9nmX9YD2WtZKQZOQbnwZkJzvy1', 'mariatua2@hotmail.com', 'mary10');
INSERT INTO public.account (uid, email, username) VALUES ('lzX10JlxAkYVkFvD3GL2mxZdKDj1', 'mary11@hotmail.com', 'mary11');
INSERT INTO public.account (uid, email, username) VALUES ('lFncaqVA3Xh0CfgGWg8TQnFq9A43', 'mary15@hotmail.com', 'mary15');
INSERT INTO public.account (uid, email, username) VALUES ('EqeANywnlBZyuq45PaOTV2iX4JI2', 'mary17@gotmail.com', 'mary17');
INSERT INTO public.account (uid, email, username) VALUES ('Ezr1MsMAkAXOgXazaaKjUEXtHaW2', 'mary16@hotmail.com', 'mary16');


-- public address
INSERT INTO public.address (id, address, "accountUid") VALUES (1, '0x5Bf823cA5b7E36EcBdb9807502592e6645D70B69', 'IjjE2ni5MVPcGdZ0Mw1w0kMV9fE2');
INSERT INTO public.address (id, address, "accountUid") VALUES (2, '0xd36DeaEE2EF17e22e47417d126FAc10843518715', 'IjjE2ni5MVPcGdZ0Mw1w0kMV9fE2');
INSERT INTO public.address (id, address, "accountUid") VALUES (3, '0x5639748458f9b69652c4479050259FeE2b5Af815', 'mIi5ID1RmLNX6aFGohu9Uo78sKh2');
INSERT INTO public.address (id, address, "accountUid") VALUES (4, '0x910bf8b7b7583a91a73bb3971d70654ed9a2f700', 'zLMEK11qxWhsXUpzIMqgoCpci8E2');
INSERT INTO public.address (id, address, "accountUid") VALUES (6, '5e6JaTNpeFCwNGhXPhztHXFewmsKCRHeXJaaMQa4aRnk', 'zLMEK11qxWhsXUpzIMqgoCpci8E2');
INSERT INTO public.address (id, address, "accountUid") VALUES (7, '0x555853680F333E238E0E05e229AE1e5a25Cb1A81', '6sjxrjS6hdO1v0v8qU5kZEuUoog2');
INSERT INTO public.address (id, address, "accountUid") VALUES (8, '0x3e8e97B0a4215ed4E4a79438E3Dcb3a2f15e6455', 'y0NGSz1XkAexvTlTNSU6rzKhtbC3');
INSERT INTO public.address (id, address, "accountUid") VALUES (11, '0x3e8e97b0a4215ed4e4a79438e3dcb3a2f15e6455', 'lFncaqVA3Xh0CfgGWg8TQnFq9A43');

-- public pinned
INSERT INTO public.pinned (id, "accountUid") VALUES ('0x0d0167a823c6619d430b1a96ad85b888bcf97c37-18471', 'IjjE2ni5MVPcGdZ0Mw1w0kMV9fE2');
INSERT INTO public.pinned (id, "accountUid") VALUES ('0x0d0167a823c6619d430b1a96ad85b888bcf97c37-11101', 'IjjE2ni5MVPcGdZ0Mw1w0kMV9fE2');
INSERT INTO public.pinned (id, "accountUid") VALUES ('0x0d0167a823c6619d430b1a96ad85b888bcf97c37-14466', 'IjjE2ni5MVPcGdZ0Mw1w0kMV9fE2');
INSERT INTO public.pinned (id, "accountUid") VALUES ('0x0d0167a823c6619d430b1a96ad85b888bcf97c37-16531', 'IjjE2ni5MVPcGdZ0Mw1w0kMV9fE2');
INSERT INTO public.pinned (id, "accountUid") VALUES ('0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85-20234006838621431500132286480027581544896844998994792344123313484368436401378', 'IjjE2ni5MVPcGdZ0Mw1w0kMV9fE2');
INSERT INTO public.pinned (id, "accountUid") VALUES ('0x375ea781c49eafedde07afe6196f885761f166ae-7503', 'IjjE2ni5MVPcGdZ0Mw1w0kMV9fE2');
